// ui/src/PlayersInGroup.tsx
import React from 'react';
import {PlayersInGroupQuery, useAddPlayerToGroupMutation, usePlayersInGroupQuery} from './graphql';
import classNames from 'classnames';
import {WithQuery} from './WithQuery';
import {useTranslation} from 'react-i18next';

interface IPlayer {
  nickname: string;
  firstName: string;
  lastName: string;
  isMemberInGroup: boolean;
}

function PlayerToggleButton({groupName, player, onChange}: { groupName: string, player: IPlayer, onChange: () => void }): JSX.Element {

  const {firstName, lastName, isMemberInGroup} = player;
  const [addPlayerToGroup] = useAddPlayerToGroupMutation();

  function toggleGroupMembership(): void {
    addPlayerToGroup({variables: {groupName, playerName: player.nickname, newState: !isMemberInGroup}})
      .then(({data}) => data && onChange())
      .catch((error) => console.info(error));
  }

  return (
    <button className={classNames('button', 'is-fullwidth', {'is-link': isMemberInGroup})} onClick={toggleGroupMembership}>
      {isMemberInGroup ? <span>&#10004;</span> : <span>&#10008;</span>} {firstName} {lastName}
    </button>
  );
}

interface IProps {
  groupName: string;
}

export function PlayersInGroup({groupName}: IProps): JSX.Element {

  const {t} = useTranslation('common');
  const playersInGroupQuery = usePlayersInGroupQuery({variables: {groupName}});

  function render({players}: PlayersInGroupQuery): JSX.Element {
    if (players.length === 0) {
      return <div className="notification is-warning has-text-centered">{t('noPlayersFound')}</div>;
    }

    return (
      <div className="columns is-multiline">
        {players.map((player) =>
          <div className="column is-2" key={player.nickname}>
            <PlayerToggleButton groupName={groupName} player={player} onChange={playersInGroupQuery.refetch}/>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="container">
      <h1 className="title is-3 has-text-centered">{t('group')} {groupName}: {t('players')}</h1>

      <WithQuery query={playersInGroupQuery} render={render}/>
    </div>
  );
}

// ui/src/app/players-in-group/players-in-group.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {ApiService} from '../_services/api.service';
import {GroupWithPlayersAndMembership} from '../_interfaces/group';
import {Player} from '../_interfaces/interfaces';

@Component({templateUrl: './players-in-group.component.html'})
export class PlayersInGroupComponent implements OnInit {

  group: GroupWithPlayersAndMembership;

  constructor(private route: ActivatedRoute, private apiService: ApiService) {
  }

  ngOnInit(): void {
    this.route.paramMap.subscribe((paramMap) => {
      const groupId = parseInt(paramMap.get('groupId'), 10);

      this.apiService.getGroupWithPlayersAndMembership(groupId)
        .subscribe((group) => {
          this.group = group;

          console.info(JSON.stringify(this.group.players, null, 2));
        });
    });
  }

  addPlayerToGroup(p: { player: Player, isMember: boolean }): void {
    this.apiService.addPlayerToGroup(this.group.group.id, p.player.id)
      .subscribe((isMember) => p.isMember = isMember);
  }

}

<div class="container">
  <h1 class="title is-3 has-text-centered">Gruppe {{groupName}}: Spieler</h1>

  <ng-container *ngIf="playersInGroupQuery; else loadingDataComponent">

    <div class="columns is-multiline" *ngIf="playersInGroupQuery.players; else noPlayersFoundBlock">

      <div class="column is-2" *ngFor="let player of playersInGroupQuery.players">
        <button class="button is-fullwidth" [class.is-link]="player.isMemberInGroup"
                (click)="toggleGroupMembership(player.nickname, !player.isMemberInGroup)">
          {{player.isMemberInGroup ? '&#10004;' : '&#10008;'}} {{player.firstName}} {{player.lastName}}
        </button>
      </div>

    </div>

  </ng-container>

</div>

<ng-template #loadingDataComponent>
  <div class="notification is-primary has-text-centered">Lade Daten...</div>
</ng-template>

<ng-template #noPlayersFoundBlock>
  <div class="notification is-warning has-text-centered">Keine Spieler gefunden!</div>
</ng-template>
