// react-ui/src/LoginForm.tsx
import React, {Dispatch} from 'react';
import {useTranslation} from 'react-i18next';
import {Credentials, useLoginMutation} from './graphql';
import * as yup from 'yup';
import {ErrorMessage, Field, Form, Formik} from 'formik';
import classNames from 'classnames';
import {useDispatch, useSelector} from 'react-redux';
import {currentUserSelector} from './store/store';
import {Redirect} from 'react-router-dom';
import {StoreAction, userLoginAction} from './store/actions';

const initialValues: Credentials = {username: '', password: ''};

const credentialsSchema: yup.SchemaOf<Credentials> = yup.object()
  .shape({
    username: yup.string().required(),
    password: yup.string().required()
  })
  .required();

export function LoginForm(): JSX.Element {

  const {t} = useTranslation('common');
  const [login, {loading, error}] = useLoginMutation();
  const dispatch = useDispatch<Dispatch<StoreAction>>();
  const currentUser = useSelector(currentUserSelector);

  if (currentUser) {
    return <Redirect to={'/'}/>;
  }

  function onSubmit(credentials: Credentials): void {
    login({variables: {credentials}})
      .then(({data}) => data?.login && dispatch(userLoginAction(data.login)))
      .catch((error) => console.error(error));
  }

  return (
    <div className="container">
      <h1 className="title is-3 has-text-centered">{t('login')}</h1>

      <Formik initialValues={initialValues} validationSchema={credentialsSchema} onSubmit={onSubmit}>

        {({touched, errors}) =>
          <Form>

            <div className="field">
              <label htmlFor="username" className="label">{t('username')}:</label>
              <div className="control">
                <Field type="text" name="username" id="username" placeholder={t('username')} autoFocus
                       className={classNames('input', {'is-danger': touched.username && errors.username})}/>
              </div>
              <ErrorMessage name="username">{(msg) => <p className="help is-danger">{msg}</p>}</ErrorMessage>
            </div>

            <div className="field">
              <label htmlFor="password" className="label">{t('password')}</label>
              <div className="control">
                <Field type="password" name="password" id="password" placeholder={t('password')}
                       className={classNames('input', {'is-danger': touched.password && errors.password})}/>
              </div>
              <ErrorMessage name="password">{(msg) => <p className="help is-danger">{msg}</p>}</ErrorMessage>
            </div>

            {error && <div className="notification is-danger has-text-centered">{error.message}</div>}

            <div className="my-3">
              <button type="submit" className={classNames('button', 'is-link', 'is-fullwidth', {'is-loading': loading})} disabled={loading}>
                {t('login')}
              </button>
            </div>
          </Form>
        }

      </Formik>

    </div>
  );
}

// ui/src/app/_forms/login-form/login-form.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {ActivatedRoute, Router} from '@angular/router';
import {AuthenticationService} from '../../_services/authentication.service';
import {first} from 'rxjs/operators';
import {Credentials} from '../../_services/apollo_services';
import {GraphQLError} from 'graphql';

@Component({templateUrl: './login-form.component.html'})
export class LoginFormComponent implements OnInit {

  loginForm: FormGroup;

  submitted = false;
  loading = false;

  returnUrl: string;

  queryError: GraphQLError;

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private authenticationService: AuthenticationService,
  ) {

    if (this.authenticationService.currentUserValue) {
      // noinspection JSIgnoredPromiseFromCall
      this.router.navigate(['/']);
    }
  }

  ngOnInit() {
    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required]
    });

    this.returnUrl = this.route.snapshot.queryParams.returnUrl || '/';
  }

  get f() {
    return this.loginForm.controls;
  }

  onSubmit() {
    this.submitted = true;

    if (this.loginForm.invalid) {
      alert('Daten sind nicht valide!');
      return;
    }

    const credentials: Credentials = {
      username: this.loginForm.controls.username.value,
      password: this.loginForm.controls.password.value
    };

    this.loading = true;

    this.authenticationService.login(credentials)
      .pipe(first())
      .subscribe(
        ({data}) => {
          this.loading = false;

          if (data.login) {
            this.router.navigate([this.returnUrl]);
          }
        },
        (queryError: GraphQLError) => {
          this.queryError = queryError;
          this.loading = false;
        }
      );
  }
}

<div class="container">
  <h1 class="title is-3 has-text-centered">Login</h1>

  <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
    <div class="field">
      <label for="username" class="label">Nutzername</label>
      <div class="control">
        <input type="text" id="username" formControlName="username" class="input" placeholder="Nutzername" autofocus>
      </div>
      <p *ngIf="submitted && f.username.errors && f.username.errors.required" class="help is-danger">
        Nutzername darf nicht leer sein!
      </p>
    </div>

    <div class="field">
      <label for="password" class="label">Passwort</label>
      <div class="control">
        <input type="password" formControlName="password" placeholder="Passwort" id="password" class="input">
      </div>
      <p *ngIf="submitted && f.password.errors && f.password.errors.required" class="help is-danger">
        Passwort darf nicht leer sein!
      </p>
    </div>

    <div *ngIf="queryError" class="notification is-danger has-text-centered">
      {{queryError.message}}
    </div>

    <div class="field">
      <div class="control">
        <button class="button is-link is-fullwidth" [class.is-loading]="loading">Login</button>
      </div>
    </div>

  </form>
</div>
