// react-ui/src/sessions/GamesTable.tsx
import React from 'react';
import {GameType, SessionGameFragment, SessionPlayerFragment} from '../graphql';

interface IProps {
  players: SessionPlayerFragment[];
  games: SessionGameFragment[];
}

export function GamesTable({players, games}: IProps): JSX.Element {

  const sessionResults = new Map(
    players.map((p) => {
      let saldo = 0;
      let wonGames = 0;
      let playedGames = 0;
      let putCount = 0;

      games.forEach((game) => {
        const hasWon = game.playersHavingWonNicknames.includes(p.nickname);
        const isPlayer = game.actingPlayerNickname === p.nickname;
        const priceIsTripled = game.gameType !== GameType.Ruf && isPlayer;

        saldo += (hasWon ? 1 : -1) * (priceIsTripled ? 3 : 1) * game.price;

        if (hasWon) {
          wonGames++;
        }
        if (isPlayer) {
          playedGames++;
        }
        if (game.playersHavingPutNicknames.includes(p.nickname)) {
          putCount++;
        }
      });

      return [p.nickname, {saldo, wonGames, playedGames, putCount}];
    })
  );

  function getDealer(gameId: number): SessionPlayerFragment {
    return players[(gameId - 1) % 4];
  }

  return (
    <>
      <div className="box">
        <table className="table is-fullwidth">
          <thead>
            <tr>
              <th/>
              {players.map(({nickname}) => <th key={nickname}>{nickname}</th>)}
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>Saldo</th>
              {players.map((player) =>
                <td className={sessionResults.get(player.nickname)!.saldo < 0 ? 'has-text-danger' : 'has-text-success'} key={player.nickname}>
                  {sessionResults.get(player.nickname)!.saldo}
                </td>)}
            </tr>
            <tr>
              <th># Leger / Spiele / Gewonnen</th>
              {players.map((player) =>
                <td key={player.nickname}>
                  {sessionResults.get(player.nickname)!.putCount}
                  /
                  {sessionResults.get(player.nickname)!.playedGames}
                  /
                  {sessionResults.get(player.nickname)!.wonGames}
                </td>)}
            </tr>
          </tbody>
        </table>
      </div>

      <div className="box">
        <div className="table-container">
          <table className="table is-striped is-fullwidth">
            <thead>
              <tr>
                <th title="Nummer">#</th>
                <th>Geber</th>
                <th title="Gedoppelt">2x</th>
                <th>Leger</th>
                <th>Spiel</th>
                <th>Farbe</th>
                <th>Spieler</th>
                <th>Kontra</th>
                <th>Gewinner</th>
                <th>Laufende</th>
                <th title="Schneider / Schwarz">SN / SW</th>
                <th>Preis</th>
              </tr>
            </thead>
            <tbody>
              {games.map((playedGame) =>
                <tr key={playedGame.id}>
                  <td>{playedGame.id}</td>
                  <td>{getDealer(playedGame.id).nickname}</td>
                  <td>{playedGame.isDoubled && <span>&#10004;</span> }</td>
                  <td>{playedGame.playersHavingPutNicknames.join(', ')}</td>
                  <td>{playedGame.gameType}</td>
                  <td>{/*getSuitGermanName(*/playedGame.suit/*)*/}</td>
                  <td>{playedGame.actingPlayerNickname}</td>
                  <td>{playedGame.kontra}</td>
                  <td>{playedGame.playersHavingWonNicknames.join(', ')}</td>
                  <td>{playedGame.laufendeCount}</td>
                  <td>{playedGame.schneiderSchwarz}</td>
                  <td>{playedGame.price}</td>
                </tr>)}
              {/*
    <tr *ngIf="runningGame" className="is-selected">
    <td></td>
    <td>{{getDealer(nextGameId()).nickname}}</td>
    <td>{{runningGame.isDoubled ? '&#10004;' : ''}}</td>
    <td>
      <skl-player-abbreviations
      [players]="playersHavingPut(runningGame.playersHavingPutNicknames)"></skl-player-abbreviations>
  </td>
  <td>{{runningGame.gameType}}</td>
  <td>{{getSuitGermanName(runningGame.suit)}}</td>
  <td>{{currentActingPlayer ? currentActingPlayer.nickname : ''}}</td>
  <td>{{runningGame.kontra}}</td>
  <td>
    <skl-player-abbreviations
    [players]="playersHavingWon(runningGame.playersHavingWonNicknames)"></skl-player-abbreviations>
</td>
  <td>{{runningGame.laufendeCount}}</td>
  <td>{{runningGame.schneiderSchwarz}}</td>
  <td></td>
</tr>
*/}
            </tbody>
          </table>
        </div>
      </div>
    </>

  );

}

// ui/src/app/_components/games-table/games-table.component.ts
import {Component, Input, OnChanges, OnInit, SimpleChanges} from '@angular/core';
import {CompleteSession, Game, Player} from '../../_interfaces/interfaces';
import {SUITS} from '../../_interfaces/game_types';

@Component({
  selector: 'skl-games-table',
  templateUrl: './games-table.component.html'
})
export class GamesTableComponent implements OnInit, OnChanges {

  @Input() session: CompleteSession;

  @Input() runningGame: Game | undefined;

  players: Player[];

  currentActingPlayer: Player | undefined;

  private saldosForPlayers: Map<number, number>;

  ngOnInit(): void {
    this.players = [
      this.session.firstPlayer,
      this.session.secondPlayer,
      this.session.thirdPlayer,
      this.session.fourthPlayer
    ];

    this.updateSaldos();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this.runningGame && this.runningGame.actingPlayerId) {
      this.currentActingPlayer = this.players.find((p) => p.id === this.runningGame.actingPlayerId);
    }

    this.updateSaldos();
  }

  private updateSaldos(): void {
    if (this.players) {
      this.saldosForPlayers = new Map(
        this.players.map((p) => {
          const saldo = this.session.playedGames.map((game) => {
            const priceIsTripled = game.game.gameType !== 'Ruf' && game.game.actingPlayerId === p.id;

            if (game.game.playersHavingWonIds.includes(p.id)) {
              return (priceIsTripled ? 3 : 1) * game.price;
            } else {
              return (priceIsTripled ? -3 : -1) * game.price;
            }
          }).reduce((x, y) => x + y, 0);


          return [p.id, saldo];
        })
      );
    }
  }

  getSaldoForPlayer(playerId: number): number | undefined {
    return this.saldosForPlayers.get(playerId);
  }

  getDealer(playedGame: Game): Player {
    return this.players[(playedGame.id - 1) % 4];
  }

  getSuitGermanName(playedGame: Game): string {
    return playedGame.suit ? SUITS.find((s) => s.commitableSuit === playedGame.suit).name : '';
  }

  getActingPlayer(playedGame: Game): Player {
    return this.players.find((p) => p.id === playedGame.actingPlayerId);
  }

  playersHavingPut(playedGame: Game): Player[] {
    return this.players.filter((p) => playedGame.playersHavingPutIds.includes(p.id));
  }

  playersHavingWon(playedGame: Game): Player[] {
    return this.players.filter((p) => playedGame.playersHavingWonIds.includes(p.id));
  }

}

<div class="columns">
  <div class="column" *ngFor="let player of players">
    <div class="box">
      <span class="has-text-weight-bold">{{player.abbreviation}}</span>: {{getSaldoForPlayer(player.id)}}
    </div>

  </div>
</div>

<div class="box">
  <div class="table-container">
    <table class="table is-striped is-fullwidth">
      <thead>
      <tr>
        <th title="Nummer">#</th>
        <th>Geber</th>
        <th title="Gedoppelt">2x</th>
        <th>Leger</th>
        <th>Spiel</th>
        <th>Farbe</th>
        <th>Spieler</th>
        <th>Kontra</th>
        <th>Gewinner</th>
        <th>Laufende</th>
        <th title="Schneider / Schwarz">SN / SW</th>
        <th>Preis</th>
      </tr>
      </thead>
      <tbody>
      <tr *ngFor="let playedGame of session.playedGames">
        <td>{{playedGame.game.id}}</td>
        <td>{{getDealer(playedGame.game).abbreviation}}</td>
        <td>{{playedGame.game.isDoubled ? '&#10004;' : ''}}</td>
        <td>
          <skl-player-abbreviations [players]="playersHavingPut(playedGame.game)"></skl-player-abbreviations>
        </td>
        <td>{{playedGame.game.gameType}}</td>
        <td>{{getSuitGermanName(playedGame.game)}}</td>
        <td>{{getActingPlayer(playedGame.game).abbreviation}}</td>
        <td>{{playedGame.game.kontra}}</td>
        <td>
          <skl-player-abbreviations [players]="playersHavingWon(playedGame.game)"></skl-player-abbreviations>
        </td>
        <td>{{playedGame.game.laufendeCount}}</td>
        <td>{{playedGame.game.schneiderSchwarz}}</td>
        <td>{{playedGame.price}}</td>
      </tr>
      <tr *ngIf="runningGame" class="is-selected">
        <td>{{runningGame.id}}</td>
        <td>{{getDealer(runningGame).abbreviation}}</td>
        <td>{{runningGame.isDoubled ? '&#10004;' : ''}}</td>
        <td>
          <skl-player-abbreviations [players]="playersHavingPut(runningGame)"></skl-player-abbreviations>
        </td>
        <td>{{runningGame.gameType}}</td>
        <td>{{getSuitGermanName(runningGame)}}</td>
        <td>{{currentActingPlayer ? currentActingPlayer.abbreviation : ''}}</td>
        <td>{{runningGame.kontra}}</td>
        <td>
          <skl-player-abbreviations [players]="playersHavingWon(runningGame)"></skl-player-abbreviations>
        </td>
        <td>{{runningGame.laufendeCount}}</td>
        <td>{{runningGame.schneiderSchwarz}}</td>
        <td></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
