// react-ui/src/RegisterForm.tsx
import React from 'react';
import {RegisterUserInput, useRegisterMutation} from './graphql';
import {ErrorMessage, Field, Form, Formik} from 'formik';
import {useTranslation} from 'react-i18next';
import classNames from 'classnames';
import * as yup from 'yup';

const initialValues: RegisterUserInput = {
  username: '', password: '', passwordRepeat: ''
};

const registerUserInputSchema: yup.SchemaOf<RegisterUserInput> = yup.object()
  .shape({
    username: yup.string().min(4).required(),
    password: yup.string().min(4).required(),
    passwordRepeat: yup.string().min(4).required()
  })
  .required();

export function RegisterForm(): JSX.Element {

  const {t} = useTranslation('common');
  const [register, {data, loading, error}] = useRegisterMutation();

  function onSubmit(registerUserInput: RegisterUserInput): void {
    register({variables: {registerUserInput}})
      .catch((error) => console.error(error));
  }

  return (
    <div className="container">
      <h1 className="title is-3 has-text-centered">{t('registerNewAccount')}</h1>

      <Formik initialValues={initialValues} validationSchema={registerUserInputSchema} onSubmit={onSubmit}>
        {({touched, errors}) =>
          <Form>

            <div className="field">
              <label htmlFor="username" className="label">{t('username')}:</label>
              <div className="control">
                <Field type="text" name="username" id="username" placeholder={t('username')} autoFocus
                       className={classNames('input', {'is-danger': touched.username && errors.username})}/>
              </div>
              <ErrorMessage name="username">{(msg) => <p className="help is-danger">{msg}</p>}</ErrorMessage>
            </div>

            <div className="field">
              <label htmlFor="password" className="label">{t('password')}:</label>
              <div className="control">
                <Field type="password" name="password" id="password" placeholder={t('password')}
                       className={classNames('input', {'is-danger': touched.password && errors.password})}/>
              </div>
              <ErrorMessage name="password">{(msg) => <p className="help is-danger">{msg}</p>}</ErrorMessage>
            </div>

            <div className="field">
              <label htmlFor="passwordRepeat">{t('passwordRepeat')}:</label>
              <div className="control">
                <Field type="password" name="passwordRepeat" id="passwordRepeat" placeholder={t('passwordRepeat')}
                       className={classNames('input', {'is-danger': touched.passwordRepeat && errors.passwordRepeat})}/>
              </div>
              <ErrorMessage name="passwordRepeat">{(msg) => <p className="help is-danger">{msg}</p>}</ErrorMessage>
            </div>

            {error && <div className="notification is-danger has-text-centered">{error.message}</div>}

            {data && <div className="notification is-success has-text-centered">{t('userSuccessfullyRegeistered_{{name}}', {name: data.registerUser})}</div>}

            <div className="my-3">
              <button type="submit" className={classNames('button', 'is-link', 'is-fullwidth', {'is-loading': loading})} disabled={loading}>
                {t('registerNewAccount')}
              </button>
            </div>

          </Form>
        }
      </Formik>
    </div>
  );
}

// ui/src/app/_forms/register-form/register-form.component.ts
import {Component, OnInit} from '@angular/core';
import {RegisterGQL, RegisterUserInput} from '../../_services/apollo_services';
import {GraphQLError} from 'graphql';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';

@Component({templateUrl: './register-form.component.html'})
export class RegisterFormComponent implements OnInit {

  registerForm: FormGroup;

  submitted = false;
  loading = false;

  queryError: GraphQLError;
  registeredUsername: string;

  constructor(private fb: FormBuilder, private registerMutation: RegisterGQL) {
  }

  ngOnInit() {
    // FIXME: validator for password equality!
    this.registerForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required],
      passwordRepeat: ['', Validators.required]
    });
  }

  register(): void {
    this.submitted = true;

    const password = this.registerForm.controls.password.value;
    const passwordRepeat = this.registerForm.controls.passwordRepeat.value;

    if (this.registerForm.invalid || password !== passwordRepeat) {
      alert('One of your fields is not valid!');
      return;
    }

    const registerUserInput: RegisterUserInput = {
      username: this.registerForm.controls.username.value,
      password,
      passwordRepeat
    };

    this.loading = true;

    this.registerMutation
      .mutate({registerUserInput})
      .subscribe(
        ({data}) => {
          this.queryError = null;
          this.registeredUsername = data.registerUser;
          this.loading = false;
        },
        (error: GraphQLError) => {
          this.queryError = error;
          this.registeredUsername = null;
          this.loading = false;
        }
      );

  }

}

<div class="container">
  <h1 class="title is-3 has-text-centered">Neuen Account registrieren</h1>

  <form [formGroup]="registerForm" (ngSubmit)="register()">
    <div class="field">
      <label class="label" for="username">Nutzername:</label>
      <div class="control">
        <input type="text" id="username" formControlName="username" class="input" placeholder="Nutzername" autofocus>
      </div>
    </div>

    <div class="field">
      <label for="password" class="label">Passwort:</label>
      <div class="control">
        <input type="password" id="password" formControlName="password" class="input" placeholder="Passwort">
      </div>
    </div>

    <div class="field">
      <label for="passwordRepeat" class="label">Passwort wiederholen:</label>
      <div class="control">
        <input type="password" id="passwordRepeat" formControlName="passwordRepeat" class="input"
               placeholder="Passwort wiederholen">
      </div>
    </div>

    <div class="buttons">
      <button class="button is-link is-fullwidth" [class.is-loading]="loading">Registrieren</button>
    </div>
  </form>

  <div class="notification is-danger has-text-centered my-3" *ngIf="queryError">
    Es gab einen Fehler: {{queryError.message}}
  </div>

  <div class="notification is-success has-text-centered my-3" *ngIf="registeredUsername">
    Nutzer {{registeredUsername}} wurde erfolgreich registriert.
  </div>


</div>
